import os
SECRET_KEY='sdkfdhdshdhhUYSDIUISJH73489BSHNSDHFKLDSVNCHDS'
SQLALCHEMY_DATABASE_URI=os.getenv("DATABASE_URL")
SQLALCHEMY_TRACK_MODIFICATIONS=False

MAIL_SERVER='smtp.gmail.com'
MAIL_PORT=465
MAIL_USERNAME='frrutts@gmail.com'
MAIL_PASSWORD='rldioosiuwpkufwa'  
MAIL_USE_SSL=True