"""empty message

Revision ID: 07033e155f6d
Revises: 4c51167b2905
Create Date: 2025-08-11 08:42:08.273400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07033e155f6d'
down_revision = '4c51167b2905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('plan_frequency',
               existing_type=mysql.ENUM('weekly', 'biweekly', 'monthly'),
               type_=sa.Enum('weekly', 'one_off', 'monthly'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('plan_frequency',
               existing_type=sa.Enum('weekly', 'one_off', 'monthly'),
               type_=mysql.ENUM('weekly', 'biweekly', 'monthly'),
               existing_nullable=False)

    # ### end Alembic commands ###
