"""empty message

Revision ID: 091e881463c1
Revises: 609caf9bebce
Create Date: 2025-08-11 17:03:27.394866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091e881463c1'
down_revision = '609caf9bebce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_status', sa.Enum('active', 'inactive', 'cancelled'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('sub_status')

    # ### end Alembic commands ###
