"""empty message

Revision ID: 0a0854e10b9e
Revises: a3779c3b52df
Create Date: 2025-08-10 12:55:58.777003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0854e10b9e'
down_revision = 'a3779c3b52df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'plan', ['order_plan_id'], ['plan_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_plan_id')

    # ### end Alembic commands ###
