"""empty message

Revision ID: 0fbff159ebe9
Revises: be6acb906d1e
Create Date: 2025-08-03 21:45:04.421231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fbff159ebe9'
down_revision = 'be6acb906d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_delivery_status',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('pending', 'paid'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_delivery_status',
               existing_type=sa.Enum('pending', 'paid'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
