"""empty message

Revision ID: 27eb5ffebf27
Revises: 091e881463c1
Create Date: 2025-08-24 23:34:17.431246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27eb5ffebf27'
down_revision = '091e881463c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_authorization_code', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('sub_authorization_code')

    # ### end Alembic commands ###
