"""empty message

Revision ID: 33a88225667b
Revises: 4c98044193fe
Create Date: 2025-07-26 17:18:13.418501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33a88225667b'
down_revision = '4c98044193fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('plan_updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('box_updated_at')
        batch_op.drop_column('box_created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box_created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('box_updated_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('plan_updated_at')
        batch_op.drop_column('plan_created_at')

    # ### end Alembic commands ###
