"""empty message

Revision ID: 4c51167b2905
Revises: 0a0854e10b9e
Create Date: 2025-08-11 08:36:25.469988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c51167b2905'
down_revision = '0a0854e10b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('pay_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_method', mysql.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
