"""empty message

Revision ID: 4c98044193fe
Revises: 517c9fcdf497
Create Date: 2025-07-26 17:15:45.083264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c98044193fe'
down_revision = '517c9fcdf497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box',
    sa.Column('box_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('box_name', sa.String(length=200), nullable=True),
    sa.Column('box_size', sa.String(length=200), nullable=True),
    sa.Column('box_price', sa.Integer(), nullable=True),
    sa.Column('box_content', sa.String(length=2000), nullable=True),
    sa.Column('box_created_at', sa.DateTime(), nullable=True),
    sa.Column('box_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('box_id')
    )
    op.create_table('plan',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_frequency', sa.Enum('weekly', 'biweekly', 'monthly'), nullable=False),
    sa.Column('box_created_at', sa.DateTime(), nullable=True),
    sa.Column('box_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_user_id', sa.Integer(), nullable=True),
    sa.Column('order_box_id', sa.Integer(), nullable=True),
    sa.Column('order_pay_status', sa.Integer(), nullable=True),
    sa.Column('is_one_time', sa.Boolean(), nullable=True),
    sa.Column('is_reoccuring', sa.Boolean(), nullable=True),
    sa.Column('order_created_at', sa.DateTime(), nullable=True),
    sa.Column('order_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_box_id'], ['box.box_id'], ),
    sa.ForeignKeyConstraint(['order_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('plan')
    op.drop_table('box')
    # ### end Alembic commands ###
