"""empty message

Revision ID: 517c9fcdf497
Revises: 
Create Date: 2025-07-26 16:27:37.618659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517c9fcdf497'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fname', sa.String(length=500), nullable=False),
    sa.Column('user_lname', sa.String(length=500), nullable=False),
    sa.Column('user_email', sa.String(length=300), nullable=False),
    sa.Column('user_password', sa.String(length=500), nullable=False),
    sa.Column('user_address', sa.String(length=500), nullable=True),
    sa.Column('user_phone', sa.String(length=20), nullable=True),
    sa.Column('user_dp', sa.String(length=200), nullable=True),
    sa.Column('user_status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('user_date_created', sa.DateTime(), nullable=True),
    sa.Column('user_date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
