"""empty message

Revision ID: 609caf9bebce
Revises: 85a903aacb57
Create Date: 2025-08-11 17:03:02.976941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '609caf9bebce'
down_revision = '85a903aacb57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('sub_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_status', mysql.ENUM('active', 'inactive'), nullable=True))

    # ### end Alembic commands ###
