"""empty message

Revision ID: 85a903aacb57
Revises: 916206fe8f50
Create Date: 2025-08-11 14:27:57.713537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a903aacb57'
down_revision = '916206fe8f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_frequency', sa.Enum('weekly', 'one_off', 'biweekly', 'monthly'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('plan_frequency')

    # ### end Alembic commands ###
