"""empty message

Revision ID: 916206fe8f50
Revises: 07033e155f6d
Create Date: 2025-08-11 14:27:38.696983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '916206fe8f50'
down_revision = '07033e155f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('plan_frequency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_frequency', mysql.ENUM('weekly', 'one_off', 'monthly'), nullable=False))

    # ### end Alembic commands ###
