"""empty message

Revision ID: a3779c3b52df
Revises: 670e0666612e
Create Date: 2025-08-04 04:57:45.582345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3779c3b52df'
down_revision = '670e0666612e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_actual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pay_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('pay_data')
        batch_op.drop_column('pay_actual')

    # ### end Alembic commands ###
