"""empty message

Revision ID: b4b0197f658b
Revises: 33a88225667b
Create Date: 2025-07-26 19:06:06.629814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4b0197f658b'
down_revision = '33a88225667b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_pay_status',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('pending', 'paid'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_pay_status',
               existing_type=sa.Enum('pending', 'paid'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
