"""empty message

Revision ID: b97ee322aa66
Revises: f895f15ce5c3
Create Date: 2025-08-01 20:16:30.183211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b97ee322aa66'
down_revision = 'f895f15ce5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruit',
    sa.Column('fruit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fruit_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('fruit_id')
    )
    op.create_table('fruit_box',
    sa.Column('fruitbox_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fruitbox_boxid', sa.Integer(), nullable=True),
    sa.Column('fruitbox_fruitid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fruitbox_boxid'], ['box.box_id'], ),
    sa.ForeignKeyConstraint(['fruitbox_fruitid'], ['fruit.fruit_id'], ),
    sa.PrimaryKeyConstraint('fruitbox_id')
    )
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box_image', sa.String(length=300), nullable=True))
        batch_op.alter_column('box_size',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Enum('Large', 'Medium', 'Small'),
               existing_nullable=True)
        batch_op.drop_column('box_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box_content', mysql.VARCHAR(length=2000), nullable=True))
        batch_op.alter_column('box_size',
               existing_type=sa.Enum('Large', 'Medium', 'Small'),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('box_image')

    op.drop_table('fruit_box')
    op.drop_table('fruit')
    # ### end Alembic commands ###
