"""empty message

Revision ID: be6acb906d1e
Revises: b97ee322aa66
Create Date: 2025-08-02 07:29:35.828919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6acb906d1e'
down_revision = 'b97ee322aa66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_email', sa.String(length=50), nullable=True),
    sa.Column('admin_pwd', sa.String(length=200), nullable=True),
    sa.Column('admin_loggedin', sa.Enum('1', '0'), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
