"""empty message

Revision ID: f722e2194aa4
Revises: 27eb5ffebf27
Create Date: 2025-09-05 00:57:20.309963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f722e2194aa4'
down_revision = '27eb5ffebf27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box_status', sa.Enum('enabled', 'disabled'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.drop_column('box_status')

    # ### end Alembic commands ###
