"""empty message

Revision ID: f895f15ce5c3
Revises: b4b0197f658b
Create Date: 2025-07-29 02:06:38.742985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f895f15ce5c3'
down_revision = 'b4b0197f658b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('sub_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_userid', sa.Integer(), nullable=True),
    sa.Column('sub_boxid', sa.Integer(), nullable=True),
    sa.Column('sub_planid', sa.Integer(), nullable=True),
    sa.Column('sub_orderid', sa.Integer(), nullable=True),
    sa.Column('sub_startdate', sa.DateTime(), nullable=True),
    sa.Column('sub_nextdeliverydate', sa.DateTime(), nullable=True),
    sa.Column('sub_status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('sub_lastdeliverydate', sa.DateTime(), nullable=True),
    sa.Column('sub_createdat', sa.DateTime(), nullable=True),
    sa.Column('sub_updatedat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sub_boxid'], ['box.box_id'], ),
    sa.ForeignKeyConstraint(['sub_orderid'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['sub_planid'], ['plan.plan_id'], ),
    sa.ForeignKeyConstraint(['sub_userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_table('payments',
    sa.Column('pay_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pay_orderid', sa.Integer(), nullable=True),
    sa.Column('pay_subid', sa.Integer(), nullable=True),
    sa.Column('pay_userid', sa.Integer(), nullable=True),
    sa.Column('pay_amount', sa.Integer(), nullable=True),
    sa.Column('pay_method', sa.String(length=200), nullable=True),
    sa.Column('pay_status', sa.Enum('pending', 'successful'), nullable=True),
    sa.Column('pay_transactionref', sa.String(length=500), nullable=True),
    sa.Column('pay_attemptedat', sa.DateTime(), nullable=True),
    sa.Column('pay_createdat', sa.DateTime(), nullable=True),
    sa.Column('pay_updatedat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pay_orderid'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['pay_subid'], ['subscriptions.sub_id'], ),
    sa.ForeignKeyConstraint(['pay_userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('pay_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_delivery_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_delivery_status')

    op.drop_table('payments')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
